# Generated by Django 5.1.4 on 2025-01-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('languageid', models.AutoField(db_column='LanguageId', primary_key=True, serialize=False)),
                ('languagename', models.CharField(db_column='LanguageName', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'languages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('levelid', models.AutoField(db_column='LevelId', primary_key=True, serialize=False)),
                ('levelname', models.CharField(db_column='LevelName', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'levels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Postcontent',
            fields=[
                ('postcontentid', models.AutoField(db_column='PostContentId', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('content', models.TextField(db_column='Content')),
            ],
            options={
                'db_table': 'postcontent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('postid', models.AutoField(db_column='PostId', primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
                ('updatedat', models.DateTimeField(blank=True, db_column='UpdatedAt', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=9, null=True)),
                ('image', models.TextField(blank=True, db_column='Image', null=True)),
            ],
            options={
                'db_table': 'posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('questionid', models.AutoField(db_column='QuestionId', primary_key=True, serialize=False)),
                ('questiontext', models.TextField(db_column='QuestionText')),
                ('answer', models.TextField(blank=True, db_column='Answer', null=True)),
                ('createdat', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
            ],
            options={
                'db_table': 'questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sitestats',
            fields=[
                ('statid', models.AutoField(db_column='StatId', primary_key=True, serialize=False)),
                ('totalviews', models.BigIntegerField(blank=True, db_column='TotalViews', null=True)),
                ('lastupdated', models.DateTimeField(blank=True, db_column='LastUpdated', null=True)),
            ],
            options={
                'db_table': 'sitestats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='UserId', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=50, unique=True)),
                ('passwordhash', models.CharField(db_column='PasswordHash', max_length=255)),
                ('createdat', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
